# Generated by Django 5.1.6 on 2025-03-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_availabilityexception_doctoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='medical_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason_for_visit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
